#!/usr/bin/env python3

import sys
import pexpect

password = ''

def do_ssh(cmd):
    child = pexpect.spawn(f"ssh root@localhost", encoding='utf-8')
    child.logfile_read = sys.stdout
    child.expect('.*password: ')
    child.sendline(password)

    child.expect('root@.+# ')
    child.sendline(cmd)

    child.expect('root@.+# ')
    child.sendline('exit')

    child.expect(pexpect.EOF)
    child.wait()

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <command line>")
        sys.exit(1)

    do_ssh(sys.argv[1])
